= 보고
:allow-uri-read: 




=== 보고

이제 풍경을 분석하는 데 도움이 되는 보고서를 생성하고 다운로드할 수 있습니다.  사전 설계된 보고서는 장애 조치(failover)와 장애 복구(failback)를 요약하고, 모든 사이트의 복제 세부 정보를 표시하며, 지난 7일간의 작업 세부 정보를 표시합니다.

참조하다 https://docs.netapp.com/us-en/data-services-disaster-recovery/use/reports.html["재해 복구 보고서 만들기"] .



=== 30일 무료 체험

이제 NetApp Disaster Recovery 의 30일 무료 평가판에 등록할 수 있습니다.  이전에는 무료 체험 기간이 90일이었습니다.

참조하다 https://docs.netapp.com/us-en/data-services-disaster-recovery/get-started/dr-licensing.html["라이센스 설정"] .



=== 복제 계획 비활성화 및 활성화

이전 릴리스에는 일일 및 주간 일정을 지원하는 데 필요한 장애 조치 테스트 일정 구조에 대한 업데이트가 포함되었습니다.  이 업데이트를 적용하려면 새로운 일일 및 주간 장애 조치 테스트 일정을 사용할 수 있도록 모든 기존 복제 계획을 비활성화했다가 다시 활성화해야 합니다.  이는 일회성 요구 사항입니다.

방법은 다음과 같습니다.

. 메뉴에서 *복제 계획*을 선택합니다.
. 계획을 선택하고 작업 아이콘을 선택하여 드롭다운 메뉴를 표시합니다.
. *비활성화*를 선택하세요.
. 몇 분 후에 *활성화*를 선택하세요.




=== 폴더 매핑

복제 계획을 생성하고 컴퓨팅 리소스를 매핑할 때 이제 폴더를 매핑하여 데이터 센터, 클러스터 및 호스트에 대해 지정한 폴더에 VM을 복구할 수 있습니다.

자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/data-services-disaster-recovery/use/drplan-create.html["복제 계획 만들기"] .



=== 장애 조치, 장애 복구 및 테스트 장애 조치에 사용할 수 있는 VM 세부 정보

장애가 발생하고 장애 조치를 시작하거나, 장애 복구를 수행하거나, 장애 조치를 테스트하는 경우 이제 VM의 세부 정보를 확인하고 다시 시작되지 않은 VM을 식별할 수 있습니다.

참조하다 https://docs.netapp.com/us-en/data-services-disaster-recovery/use/failover.html["원격 사이트로 애플리케이션 장애 조치"] .



=== 순서가 지정된 부팅 시퀀스를 사용한 VM 부팅 지연

복제 계획을 만들 때 이제 계획에 있는 각 VM에 대한 부팅 지연을 설정할 수 있습니다.  이를 통해 VM이 시작될 순서를 설정하여 후속 우선순위 VM이 시작되기 전에 모든 우선순위 1 VM이 실행되도록 할 수 있습니다.

자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/data-services-disaster-recovery/use/drplan-create.html["복제 계획 만들기"] .



=== VM 운영 체제 정보

복제 계획을 만들면 이제 계획에 있는 각 VM의 운영 체제를 볼 수 있습니다.  이는 리소스 그룹에서 VM을 어떻게 그룹화할지 결정하는 데 유용합니다.

자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/data-services-disaster-recovery/use/drplan-create.html["복제 계획 만들기"] .



=== VM 이름 별칭

복제 계획을 만들 때 이제 재해 복구 사이트의 VM 이름에 접두사와 접미사를 추가할 수 있습니다.  이를 통해 계획에 있는 VM에 대해 보다 설명적인 이름을 사용할 수 있습니다.

자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/data-services-disaster-recovery/use/drplan-create.html["복제 계획 만들기"] .



=== 오래된 스냅샷 정리

지정한 보존 기간을 넘어서 더 이상 필요하지 않은 스냅샷은 삭제할 수 있습니다.  스냅샷 보존 횟수를 줄이면 시간이 지남에 따라 스냅샷이 누적될 수 있으며, 이제 스냅샷을 제거하여 공간을 확보할 수 있습니다.  이 작업은 언제든지 필요할 때 수행할 수 있으며, 복제 계획을 삭제할 때도 수행할 수 있습니다.

자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/data-services-disaster-recovery/use/manage.html["사이트, 리소스 그룹, 복제 계획, 데이터 저장소 및 가상 머신 정보를 관리합니다."] .



=== 스냅샷 조정

이제 소스와 대상 간에 동기화되지 않은 스냅샷을 조정할 수 있습니다.  이는 NetApp Disaster Recovery 외부의 대상에서 스냅샷이 삭제된 경우 발생할 수 있습니다.  이 서비스는 24시간마다 소스의 스냅샷을 자동으로 삭제합니다.  하지만 필요에 따라 이를 수행할 수도 있습니다.  이 기능을 사용하면 모든 사이트에서 스냅샷이 일관성을 유지하도록 할 수 있습니다.

자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/data-services-disaster-recovery/use/manage.html["복제 계획 관리"] .
