= BlueXP disaster recovery 이제 NetApp Disaster Recovery 입니다.
:allow-uri-read: 




=== BlueXP disaster recovery 이제 NetApp Disaster Recovery 입니다.

BlueXP disaster recovery NetApp Disaster Recovery 로 이름이 변경되었습니다.



=== BlueXP 는 이제 NetApp Console 입니다.

강화되고 재구성된 BlueXP 기반을 기반으로 구축된 NetApp Console 엔터프라이즈급 온프레미스 및 클라우드 환경에서 NetApp 스토리지와 NetApp Data Services 중앙에서 관리하여 실시간 통찰력, 더 빠른 워크플로, 간소화된 관리를 제공하며, 높은 보안성과 규정 준수를 보장합니다.

변경된 사항에 대한 자세한 내용은 다음을 참조하세요. link:https://docs.netapp.com/us-en/console-relnotes/index.html["NetApp Console 릴리스 노트"].



=== 기타 업데이트

* Amazon FSx for NetApp ONTAP 통한 Amazon Elastic VMware Service(EVS) 지원은 공개 미리 보기 단계에 있었습니다. 이번 릴리스를 통해 이제 일반적으로 사용할 수 있게 되었습니다. 자세한 내용은 다음을 참조하세요.link:../reference/evs-deploy-guide-introduction.html["Amazon Elastic VMware Service 및 Amazon FSx for NetApp ONTAP 사용한 NetApp Disaster Recovery 소개"] .
* 온프레미스 배포에 대한 검색 시간 단축을 포함한 스토리지 검색 개선
* 역할 기반 액세스 제어(RBAC) 및 향상된 사용자 권한을 포함한 IAM(Identity and Access Management) 지원
* Azure VMware 솔루션 및 Cloud Volumes ONTAP 에 대한 Private Preview 지원. 이 지원을 통해 이제 Cloud Volumes ONTAP 스토리지를 사용하여 온프레미스에서 Azure VMware 솔루션으로 재해 복구 보호를 구성할 수 있습니다.

