= 서브넷 매핑
:allow-uri-read: 




=== 서브넷 매핑

이 릴리스에서는 서브넷 매핑을 사용하여 새로운 방식으로 장애 조치 시 IP 주소를 관리할 수 있으며, 이를 통해 각 vCenter에 대한 서브넷을 추가할 수 있습니다.  이렇게 하면 각 가상 네트워크에 대한 IPv4 CIDR, 기본 게이트웨이, DNS가 정의됩니다.

장애 조치 시 NetApp Disaster Recovery는 매핑된 가상 네트워크에 제공된 CIDR을 보고 각 vNIC의 적절한 IP 주소를 결정하고 이를 사용하여 새 IP 주소를 파생합니다.

예를 들어:

* 네트워크A = 10.1.1.0/24
* 네트워크B = 192.168.1.0/24


VM1에는 NetworkA에 연결된 vNIC(10.1.1.50)가 있습니다.  NetworkA는 복제 계획 설정에서 NetworkB에 매핑됩니다.

장애 조치 시 NetApp Disaster Recovery는 원래 IP 주소(10.1.1)의 네트워크 부분을 대체하고 원래 IP 주소(10.1.1.50)의 호스트 주소(.50)를 유지합니다.  VM1의 경우 NetApp Disaster Recovery는 NetworkB의 CIDR 설정을 살펴보고 NetworkB의 네트워크 부분인 192.168.1을 사용하고 호스트 부분(.50)은 그대로 유지하여 VM1의 새 IP 주소를 생성합니다.  새로운 IP는 192.168.1.50이 됩니다.

요약하자면, 호스트 주소는 동일하게 유지되지만 네트워크 주소는 사이트 서브넷 매핑에 구성된 주소로 대체됩니다.  이를 통해 장애 조치 시 IP 주소 재할당을 보다 쉽게 관리할 수 있으며, 특히 관리해야 할 네트워크가 수백 개이고 VM이 수천 개일 경우 더욱 그렇습니다.

사이트에 서브넷 매핑을 포함하는 방법에 대한 자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/sites-add.html["vCenter 서버 사이트 추가"] .



=== 스킵 보호

이제 복제 계획 장애 조치 후 서비스가 자동으로 역방향 보호 관계를 생성하지 않도록 보호를 건너뛸 수 있습니다.  NetApp Disaster Recovery에서 다시 온라인으로 전환하기 전에 복원된 사이트에서 추가 작업을 수행하려는 경우 이 기능이 유용합니다.

장애 조치를 시작하면 기본적으로 서비스는 복제 계획의 각 볼륨에 대해 역방향 보호 관계를 자동으로 생성합니다(원본 소스 사이트가 온라인 상태인 경우).  즉, 서비스는 대상 사이트에서 소스 사이트로 SnapMirror 관계를 생성합니다.  또한 이 서비스는 장애 복구를 시작하면 SnapMirror 관계를 자동으로 되돌립니다.

장애 조치를 시작할 때 이제 *보호 건너뛰기* 옵션을 선택할 수 있습니다.  이를 통해 서비스는 SnapMirror 관계를 자동으로 반전시키지 않습니다.  대신 복제 계획의 양쪽에 쓰기 가능한 볼륨이 남습니다.

원래 소스 사이트가 다시 온라인 상태가 되면 복제 계획 작업 메뉴에서 *리소스 보호*를 선택하여 역방향 보호를 설정할 수 있습니다.  이는 계획의 각 볼륨에 대해 역방향 복제 관계를 생성하려고 시도합니다.  보호가 복구될 때까지 이 작업을 반복해서 실행할 수 있습니다.  보호가 복구되면 평소와 같은 방식으로 장애 복구를 시작할 수 있습니다.

자세한 내용은 건너뛰기 보호에 대한 내용을 참조하세요. https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["원격 사이트로 애플리케이션 장애 조치"] .



=== SnapMirror 복제 계획에서 업데이트를 일정에 추가합니다.

NetApp Disaster Recovery는 이제 기본 ONTAP SnapMirror 정책 스케줄러나 ONTAP 과의 타사 통합과 같은 외부 스냅샷 관리 솔루션을 사용할 수 있도록 지원합니다.  복제 계획의 모든 데이터 저장소(볼륨)에 이미 다른 곳에서 관리되는 SnapMirror 관계가 있는 경우, 해당 스냅샷을 NetApp Disaster Recovery에서 복구 지점으로 사용할 수 있습니다.

구성하려면 복제 계획 > 리소스 매핑 섹션에서 데이터 저장소 매핑을 구성할 때 *플랫폼 관리 백업 및 보존 일정 사용* 확인란을 선택합니다.

해당 옵션을 선택하면 NetApp Disaster Recovery는 백업 일정을 구성하지 않습니다.  그러나 테스트, 장애 조치 및 장애 복구 작업을 위해 스냅샷이 계속 생성될 수 있으므로 보존 일정을 구성해야 합니다.

이것이 구성된 후에는 서비스가 정기적으로 예약된 스냅샷을 찍지 않고 대신 외부 엔터티를 사용하여 해당 스냅샷을 찍고 업데이트합니다.

복제 계획에서 외부 스냅샷 솔루션을 사용하는 방법에 대한 자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획 만들기"] .
