= VM에 대한 예약된 검색
:allow-uri-read: 




=== VM에 대한 예약된 검색

NetApp Disaster Recovery 24시간마다 검색을 수행합니다.  이번 릴리스를 통해 이제 필요에 맞게 검색 일정을 사용자 지정하고 필요할 때 성능에 미치는 영향을 줄일 수 있습니다.  예를 들어, VM 수가 많은 경우 검색 일정을 48시간마다 실행되도록 설정할 수 있습니다.  VM 수가 적은 경우 검색 일정을 12시간마다 실행되도록 설정할 수 있습니다.

검색 일정을 예약하고 싶지 않으면 예약된 검색 옵션을 비활성화하고 언제든지 수동으로 검색을 새로 고칠 수 있습니다.

자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/data-services-disaster-recovery/use/sites-add.html["vCenter 서버 사이트 추가"] .



=== 리소스 그룹 데이터 저장소 지원

이전에는 VM별로만 리소스 그룹을 만들 수 있었습니다.  이 릴리스에서는 데이터 저장소별로 리소스 그룹을 만들 수 있습니다.  복제 계획을 만들고 해당 계획에 대한 리소스 그룹을 만들면 데이터 저장소의 모든 VM이 나열됩니다.  이 기능은 다수의 VM이 있고 이를 데이터 저장소별로 그룹화하려는 경우에 유용합니다.

다음과 같은 방법으로 데이터 저장소를 사용하여 리소스 그룹을 만들 수 있습니다.

* 데이터 저장소를 사용하여 리소스 그룹을 추가하는 경우 데이터 저장소 목록을 볼 수 있습니다.  하나 이상의 데이터 저장소를 선택하여 리소스 그룹을 만들 수 있습니다.
* 복제 계획을 만들고 계획 내에서 리소스 그룹을 만들면 데이터 저장소에서 VM을 볼 수 있습니다.


자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/data-services-disaster-recovery/use/drplan-create.html["복제 계획 만들기"] .



=== 무료 체험판 또는 라이센스 만료 알림

이 릴리스에서는 무료 평가판이 60일 후에 만료된다는 알림을 제공하여 라이선스를 받을 시간을 확보할 수 있도록 합니다.  이 릴리스에서는 라이센스가 만료되는 날에 대한 알림도 제공합니다.



=== 서비스 업데이트 알림

이번 릴리스에서는 서비스가 업그레이드되고 서비스가 유지 관리 모드로 전환되었음을 나타내는 배너가 상단에 나타납니다.  배너는 서비스가 업그레이드될 때 나타나고 업그레이드가 완료되면 사라집니다.  업그레이드가 진행되는 동안 UI에서 작업을 계속할 수 있지만 새로운 작업을 제출할 수는 없습니다.  업데이트가 완료되고 서비스가 프로덕션 모드로 돌아온 후에 예약된 작업이 실행됩니다.
