= NetApp Disaster Recovery 의 사용자 역할
:allow-uri-read: 




=== NetApp Disaster Recovery 의 사용자 역할

NetApp Disaster Recovery 이제 각 사용자가 특정 기능과 작업에 대해 갖는 액세스를 관리하는 역할을 사용합니다.

이 서비스는 NetApp Disaster Recovery 에 특정한 다음 역할을 사용합니다.

* *재해 복구 관리자*: NetApp Disaster Recovery 에서 모든 작업을 수행합니다.
* *재해 복구 장애 조치 관리자*: NetApp Disaster Recovery 에서 장애 조치 및 마이그레이션 작업을 수행합니다.
* *재해 복구 애플리케이션 관리자*: 복제 계획을 만들고 수정하고 테스트 장애 조치를 시작합니다.
* *재해 복구 뷰어*: NetApp Disaster Recovery 에서 정보를 볼 수 있지만, 어떤 작업도 수행할 수 없습니다.


NetApp Disaster Recovery 서비스를 클릭하고 처음으로 구성하는 경우 *SnapCenterAdmin* 권한이나 *조직 관리자* 역할이 있어야 합니다.

자세한 내용은 다음을 참조하십시오.  https://docs.netapp.com/us-en/bluexp-disaster-recovery/reference/dr-reference-roles.html["NetApp Disaster Recovery 의 사용자 역할 및 권한"] .

https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["모든 서비스에 대한 액세스 역할에 대해 알아보세요"^] .



=== NetApp Disaster Recovery 의 기타 업데이트

* 향상된 네트워크 검색
* 확장성 개선:
+
** 모든 세부 정보 대신 필요한 메타데이터만 필터링
** VM 리소스를 더 빠르게 검색하고 업데이트하기 위한 검색 개선
** 데이터 검색 및 데이터 업데이트를 위한 메모리 최적화 및 성능 최적화
** vCenter SDK 클라이언트 생성 및 풀 관리 개선


* 다음 예약 또는 수동 검색 시 오래된 데이터 관리:
+
** vCenter에서 VM이 삭제되면 이제 NetApp Disaster Recovery 복제 계획에서 자동으로 해당 VM을 제거합니다.
** vCenter에서 데이터 저장소나 네트워크가 삭제되면 이제 NetApp Disaster Recovery 복제 계획 및 리소스 그룹에서도 해당 데이터 저장소나 네트워크를 삭제합니다.
** vCenter에서 클러스터, 호스트 또는 데이터 센터가 삭제되면 이제 NetApp Disaster Recovery 복제 계획 및 리소스 그룹에서 해당 항목을 삭제합니다.


* 이제 브라우저의 시크릿 모드에서도 Swagger 문서에 액세스할 수 있습니다. NetApp Disaster Recovery 에서 설정 옵션 > API 설명서를 통해 액세스할 수 있으며, 브라우저의 시크릿 모드에서 다음 URL을 통해 직접 액세스할 수도 있습니다. https://snapcenter.cloudmanager.cloud.netapp.com/api/api-doc/draas["Swagger 문서"^] .
* 어떤 상황에서는 장애 복구 작업 후 작업이 완료된 후에도 iGroup이 남겨지는 경우가 있었습니다. 이 업데이트는 오래된 iGroup을 제거합니다.
* 복제 계획에 NFS FQDN이 사용된 경우 NetApp Disaster Recovery 이제 이를 IP 주소로 확인합니다. 이 업데이트는 재해 복구 사이트에서 FQDN을 확인할 수 없는 경우에 유용합니다.
* UI 정렬 개선
* 성공적인 검색 후 vCenter 크기 조정 세부 정보를 캡처하기 위한 로그 개선

