= Kubernetes 기반 워크로드 지원(미리 보기)
:allow-uri-read: 




=== Kubernetes 기반 워크로드 지원(미리 보기)

NetApp Disaster Recovery에 Kubernetes 기반 워크로드 지원이 추가되었습니다. Kubernetes 지원을 통해 OpenShift Virtualization 환경을 포함한 Kubernetes 클러스터에서 실행되는 애플리케이션을 보호할 수 있습니다. Disaster Recovery는 link:https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-requirements.html["Trident Protect에서 현재 지원하는 모든 Kubernetes 버전"^]를 지원하여 컨테이너화된 애플리케이션에 대한 원활한 통합과 강력한 재해 복구 기능을 제공합니다.

Kubernetes 기반 워크로드 지원의 주요 기능:

* **폭넓은 호환성**: Disaster Recovery는 Red Hat OpenShift Virtualization을 포함하여 Trident Protect와 호환되는 모든 Kubernetes 버전을 지원합니다.
* **애플리케이션 중심 보호**: 이제 애플리케이션 수준에서 Kubernetes 워크로드를 보호하여 페일오버 이벤트 발생 시 중요한 서비스의 복구를 보장할 수 있습니다.
* **간소화된 오케스트레이션**: Disaster Recovery는 VMware 환경에서 사용되는 것과 동일한 효율적인 SnapMirror 기술을 활용하여 Kubernetes 워크로드의 백업 및 복제를 자동화하는 직관적인 워크플로우를 제공합니다.


Kubernetes 기반 워크로드 지원은 현재 미리 보기로 제공됩니다. Kubernetes 기반 워크로드 보호를 시작하려면 link:https://docs.netapp.com/us-en/data-services-disaster-recovery/task-kubernetes-requirements.html["NetApp Disaster Recovery를 위한 Kubernetes 요구 사항"^]을(를) 참조하십시오.
