= 온프레미스 환경에서 여러 콘솔 에이전트 지원
:allow-uri-read: 




=== 온프레미스 환경에서 여러 콘솔 에이전트 지원

온프레미스 재해 복구를 사용하는 경우 이제 각 vCenter 인스턴스에 콘솔 에이전트를 배포하여 복원력을 향상시킬 수 있습니다.

예를 들어, 두 개의 사이트(사이트 A와 B)가 있는 경우 사이트 A에는 콘솔 에이전트 A를 vCenter 1, ONTAP 배포 1 및 ONTAP 배포 2에 연결할 수 있습니다. 사이트 B는 콘솔 에이전트 B를 vCenter 2 및 ONTAP 배포 3 및 4에 연결할 수 있습니다.

재해 복구 환경에서 콘솔 에이전트에 대한 자세한 내용은 다음을 참조하십시오. link:https://docs.netapp.com/us-en/data-services-disaster-recovery/get-started/dr-prerequisites.html#netapp-console-prerequisites["콘솔 에이전트 만들기"^].



=== 데이터스토어 기반 보호를 사용하는 복제 계획에 대해 장애 조치 후 VM을 추가합니다.

장애 조치가 발생하면 데이터스토어 기반 보호를 사용하는 모든 복제 계획에는 데이터스토어에 추가된 VM이 포함됩니다. 단, 해당 VM이 검색된 경우에 한합니다. 장애 조치가 완료되기 전에 추가된 VM에 대한 매핑 세부 정보를 제공해야 합니다.

자세한 내용은 다음을 참조하세요. link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/failover.html["장애 조치 애플리케이션"^].



=== 새 이메일 알림

재해 복구 시스템은 이제 다음과 같은 이벤트에 대한 이메일 알림을 제공합니다.

* 용량 사용 한계에 근접하고 있습니다
* 보고서 생성 완료
* 직업 실패
* 면허 만료 또는 위반 사항




=== 스웨거 개선 사항

이제 재해 복구 환경에서 Swagger 문서를 확인할 수 있습니다. 재해 복구에서 **설정**을 선택한 다음 **API 문서**를 선택하여 Swagger에 연결하거나 브라우저의 시크릿/개인 모드에서 다음 URL을 방문하세요. link:https://snapcenter.cloudmanager.cloud.netapp.com/api/api-doc/draas["https://snapcenter.cloudmanager.cloud.netapp.com/api/api-doc/draas"^].



=== 개선된 사용자 인터페이스

재해 복구 기능이 향상된 경고 및 오류 해결 기능을 제공합니다. 이번 릴리스에서는 취소된 작업이 사용자 인터페이스에 표시되지 않던 오류가 수정되었습니다. 취소된 작업이 이제 표시됩니다. 또한 동일한 대상 네트워크가 여러 개의 서로 다른 소스 네트워크에 매핑될 경우 새로운 경고 메시지가 표시됩니다.



=== 복제 계획에 기본값으로 추가된 VM 폴더 구조를 유지합니다.

복제본을 생성할 때, 새로운 기본 설정은 VM 폴더 구조를 유지하는 것입니다. 복구 대상에 원래 폴더 계층 구조가 없는 경우 재해 복구 기능이 이를 생성합니다. 원래 폴더 계층 구조를 무시하려면 이 옵션을 선택 해제하면 됩니다.

자세한 내용은 다음을 참조하세요. link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/drplan-create.html["복제 계획 만들기"^].
