---
sidebar: sidebar 
permalink: reference/evs-deploy-guide-install-connector.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter 
summary: Amazon EVS와 Amazon FSx for NetApp ONTAP 사용한 NetApp Disaster Recovery 소개.  커넥터는 모든 네트워크 위치에 설치할 수 있지만 NetApp Disaster Recovery 의 경우 DR 사이트에 커넥터를 설치하는 것이 좋습니다.  이를 통해 기본 사이트에 장애가 발생하더라도 NetApp 콘솔 UI가 콘솔 에이전트와 계속 연락하여 해당 DR 사이트 내에서 복구 프로세스를 조정할 수 있습니다. 
---
= NetApp Disaster Recovery 위한 NetApp Console 에이전트 설치
:allow-uri-read: 


[role="lead"]
NetApp Console 에이전트는 클라우드 또는 온프레미스 네트워크에서 실행되는 NetApp 소프트웨어입니다.  NetApp Console 데이터 인프라를 관리하는 데 필요한 작업을 실행합니다.  콘솔 에이전트는 필요한 모든 작업을 위해 서비스 계층으로 NetApp Disaster Recovery 소프트웨어를 지속적으로 폴링합니다.

NetApp Disaster Recovery 의 경우, 수행되는 작업은 각 서비스에 대한 기본 API를 사용하여 VMware vCenter 클러스터와 ONTAP 스토리지 인스턴스를 조정하여 온프레미스 위치에서 실행되는 프로덕션 VM에 대한 보호를 제공합니다.  콘솔 에이전트는 모든 네트워크 위치에 설치할 수 있지만 NetApp Disaster Recovery 의 경우 DR 사이트에 콘솔 에이전트를 설치하는 것이 좋습니다.  이를 통해 기본 사이트에 장애가 발생하더라도 NetApp 클라우드 기반 콘솔 UI가 콘솔 에이전트와 계속 연락하여 해당 DR 사이트 내에서 복구 프로세스를 조정할 수 있습니다.

서비스를 사용하려면 표준 모드로 콘솔 에이전트를 설치하세요.  콘솔 에이전트 설치 유형에 대해 자세히 알아보려면 다음을 방문하세요. https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["NetApp Console 배포 모드에 대해 알아보기 | NetApp 문서"^] .

콘솔 에이전트는 서비스를 사용하는 데 중요하지만, 콘솔 에이전트를 설치하는 설치 단계는 사용자의 요구 사항과 네트워크 구성에 따라 달라집니다.  이 정보에서는 설치에 대한 구체적인 지침을 제공하는 것은 범위를 벗어납니다.

Amazon AWS에 콘솔 에이전트를 설치하는 가장 간단한 방법은 AWS Marketplace를 사용하는 것입니다.  AWS Marketplace를 사용하여 콘솔 에이전트를 설치하는 방법에 대한 자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-aws-marketplace.html["AWS Marketplace에서 콘솔 에이전트 만들기 | NetApp 문서"^] .
