---
sidebar: sidebar 
permalink: reference/evs-deploy-guide-introduction.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter, netapp, ontap 
summary: Amazon EVS와 Amazon FSx for NetApp ONTAP 사용한 NetApp Disaster Recovery 소개. 
---
= Amazon Elastic VMware Service 및 Amazon FSx for NetApp ONTAP을 사용한 NetApp Disaster Recovery에 대해 알아보십시오
:allow-uri-read: 


[role="lead"]
NetApp Disaster Recovery는 온프레미스 환경의 데이터를 Amazon EVS 및 Amazon FSx for NetApp ONTAP에 복제하여 재해 복구를 위한 VMware 워크로드를 보호하는 데 도움을 줍니다.

모든 DR 솔루션의 주요 과제 중 하나는 DR 복제 및 복구 인프라를 제공하기 위해 추가적인 컴퓨팅, 네트워크 및 스토리지 리소스를 구매, 구성 및 유지 관리하는 데 드는 증가 비용을 관리하는 것입니다.  중요한 온프레미스 가상 리소스를 보호하는 데 널리 사용되는 옵션 중 하나는 클라우드 호스팅 가상 리소스를 DR 복제 및 복구 인프라로 사용하는 것입니다.  Amazon은 NetApp ONTAP 호스팅 VM 인프라와 호환되는 비용 효율적인 리소스를 제공할 수 있는 솔루션의 한 예입니다.

아마존은 가상 프라이빗 클라우드(VPC) 내에서 VMware Cloud Foundation을 사용할 수 있도록 하는 Amazon Elastic VMware Service(Amazon EVS)를 출시했습니다. Amazon EVS는 AWS의 복원력과 성능은 물론 익숙한 VMware 소프트웨어 및 툴을 제공하여 Amazon EVS vCenters가 온프레미스 가상화 인프라와 통합될 수 있도록 지원합니다.

Amazon EVS에는 기본 스토리지 리소스가 포함되어 있지만, 스토리지 사용량이 많은 워크로드를 처리하는 조직의 경우 네이티브 스토리지를 사용하면 효율성이 떨어질 수 있습니다. 이러한 경우 Amazon EVS와 Amazon FSx for NetApp ONTAP 스토리지(Amazon FSxN)를 함께 사용하면 더욱 유연한 스토리지 솔루션을 제공할 수 있습니다. 또한 온프레미스 환경에서 NetApp ONTAP 스토리지 솔루션을 사용하여 VMware 인프라를 호스팅하는 경우, Amazon EVS와 FSx for ONTAP를 함께 사용하면 온프레미스와 클라우드 환경 간의 데이터 상호 운용성과 보호 기능을 확보할 수 있습니다.

Amazon FSx for NetApp ONTAP 에 대한 정보는 다음을 참조하세요. https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/getting-started.html["Amazon FSx for NetApp ONTAP 시작하기"^] .
