---
sidebar: sidebar 
permalink: reference/evs-deploy-guide-install-connector.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter 
summary: NetApp Console 에이전트는 NetApp Console과 클라우드 또는 온프레미스 스토리지 리소스 간의 연결 및 관리를 오케스트레이션합니다. 
---
= NetApp Disaster Recovery 위한 NetApp Console 에이전트 설치
:allow-uri-read: 


[role="lead"]
NetApp Console 에이전트를 사용하면 NetApp Console 배포를 인프라에 연결하여 AWS, Azure, Google Cloud 또는 온프레미스 환경 전반에서 솔루션을 안전하게 오케스트레이션할 수 있습니다. Console 에이전트는 NetApp Console이 데이터 인프라를 관리하는 데 필요한 작업을 실행합니다. Console 에이전트는 NetApp Disaster Recovery 서비스형 소프트웨어 계층에서 수행해야 하는 작업이 있는지 지속적으로 폴링합니다.

NetApp Disaster Recovery의 경우, 수행되는 작업은 각 서비스의 네이티브 API를 사용하여 VMware vCenter 클러스터와 ONTAP 스토리지 인스턴스를 오케스트레이션하여 온프레미스 환경에서 실행되는 프로덕션 VM을 보호합니다. Console 에이전트는 네트워크의 어느 위치에든 설치할 수 있지만, NetApp Disaster Recovery의 경우 재해 복구 사이트에 Console 에이전트를 설치하는 것이 좋습니다. DR 사이트에 설치하면 기본 사이트에 장애가 발생하더라도 NetApp Console UI가 Console 에이전트와의 연결을 유지하고 해당 DR 사이트 내에서 복구 프로세스를 오케스트레이션할 수 있습니다.



== 설치

* Disaster Recovery를 사용하려면 Console 에이전트를 표준 모드로 설치하십시오. Console 에이전트 설치 유형에 대한 자세한 내용은 https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["NetApp Console 배포 모드에 대해 알아보세요"^]를 참조하십시오.


Console 에이전트의 구체적인 설치 단계는 배포 유형에 따라 다릅니다. link:https://docs.netapp.com/us-en/console-setup-admin/concept-agents.html["콘솔 에이전트에 대해 알아보세요"^]자세한 내용은 해당 문서를 참조하십시오.


TIP: Amazon AWS에 Console 에이전트를 설치하는 가장 간단한 방법은 AWS Marketplace를 이용하는 것입니다. AWS Marketplace를 사용한 Console 에이전트 설치에 대한 자세한 내용은 https://docs.netapp.com/us-en/console-setup-admin/task-install-connector-aws-marketplace.html["AWS 마켓플레이스에서 Console 에이전트를 생성하세요."^]를 참조하십시오.
