---
sidebar: sidebar 
permalink: use/task-appvault.html 
keywords: disaster recovery, appvault, update credentials, trident protect, kubernetes, edit endpoints 
summary: Disaster Recovery에서 AppVaults를 관리하면 재해 복구 계획의 연속성을 보장하기 위해 AppVaults의 연결 상태와 AppVaults의 자격 증명 및 엔드포인트를 검토할 수 있습니다. 
---
= NetApp Disaster Recovery에서 AppVaults 관리
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
NetApp Disaster Recovery 워크로드(Kubernetes 사용)는 Trident Protect가 Kubernetes 보호 데이터를 저장하는 클라우드 스토리지 대상인 AppVault를 사용합니다. AppVaults를 관리하면 AppVaults의 연결 상태와 복제 계획의 상태를 보장하기 위한 AppVaults의 자격 증명 및 엔드포인트를 검토할 수 있습니다.

*필요한 NetApp Console 역할* 이 작업을 수행하려면 Super admin, Disaster recovery admin 또는 Disaster recovery application admin 역할이 필요합니다. link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-disaster-rec-roles.html["NetApp Disaster Recovery 의 사용자 역할 및 권한에 대해 알아보세요."^]. link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["모든 서비스에 대한 NetApp Console 액세스 역할에 대해 알아보세요."^].



[[add-an-appvault]]
== AppVault 추가

Kubernetes용 복제 계획을 생성할 때 AppVault를 추가하거나 설정 페이지에서 직접 생성할 수 있습니다.

.단계
. Disaster Recovery에서 사이드바의 *설정*을 선택합니다.
. AppVault 카드에서 *+ Add AppVault*를 선택합니다.
. *이름*을 입력하고 AppVault를 연결할 *콘솔 에이전트*를 선택하십시오.
. *AppVault*를 호스팅할 클라우드 *공급자*를 선택합니다.
. 공급자 선택을 기반으로 Disaster Recovery는 기존에 구성된 클라우드 구독을 채웁니다.
+
Azure의 경우 *구독*, *리소스 그룹* 및 *스토리지 계정*을 선택하세요.

+
AWS, ONTAP S3 및 StorageGRID의 경우 *계정* 또는 *자격 증명*과 *버킷*을 선택하십시오.

. ONTAP S3 또는 StorageGRID를 선택한 경우 선택적으로 자격 증명을 추가할 수 있습니다. *자격 증명 추가*를 선택하여 옵션을 확장한 다음 *자격 증명 이름*, *게이트웨이 노드 FQDN*, *포트* 번호, *액세스 키* 및 *비밀 키*를 추가하십시오.
. **추가**를 선택합니다.




[[update-appvault-credentials]]
== AppVault 자격 증명 업데이트

AppVault의 자격 증명이 변경된 경우, 복제 계획의 연속성을 유지하려면 설정 페이지에서 자격 증명을 업데이트하십시오. 자격 증명을 업데이트하면 이 자격 증명을 공유하는 모든 AppVault의 키가 교체됩니다.

.단계
. Disaster Recovery에서 사이드바의 *설정*을 선택합니다.
. *AppVaults 관리*를 선택합니다.
. 업데이트할 AppVault를 찾습니다. 작업 메뉴에서 *업데이트*를 선택합니다.
. 변경 사항의 영향을 받는 AppVaults 및 복제 계획의 수를 검토하십시오.
. 새로운 *비밀 키*와 *액세스 키*를 입력합니다.
. 변경 사항을 적용하려면 *자격 증명 업데이트*를 선택합니다.




[[edit-an-appvault-endpoint]]
== AppVault 엔드포인트 편집

AppVault에 대한 연결 설정이 변경된 경우 Kubernetes 워크로드에 대한 복제 계획의 연속성을 보장하기 위해 설정을 업데이트하십시오.

.단계
. Disaster Recovery에서 사이드바의 *설정*을 선택합니다.
. *AppVaults 관리*를 선택합니다.
. 편집하려는 AppVault를 찾습니다. 작업 메뉴에서 *편집*을 선택합니다.
. 새 AppVault 엔드포인트를 입력합니다.
. 새 엔드포인트를 적용하려면 *저장*을 선택합니다.




[[delete-an-appvault]]
== AppVault 삭제

더 이상 AppVault가 필요하지 않으면 삭제할 수 있습니다.

.단계
. Disaster Recovery에서 사이드바의 *설정*을 선택합니다.
. *AppVaults 관리*를 선택합니다.
. 삭제하려는 AppVault를 찾습니다. 작업 메뉴에서 *삭제*를 선택합니다.
. 대화창에서 *삭제*를 선택하여 작업을 확인합니다.

