---
sidebar: sidebar 
permalink: get-started/dr-prerequisites.html 
keywords: what are disaster recovery requirements, disaster recovery prerequisites, bluexp, disaster recovery 
summary: NetApp Disaster Recovery 사용하기 전에 해당 환경이 ONTAP 스토리지, VMware vCenter 클러스터 및 NetApp Console 요구 사항을 충족하는지 확인하세요. 
---
= NetApp Disaster Recovery 필수 구성 요소
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
NetApp Disaster Recovery 사용하기 전에 해당 환경이 ONTAP 스토리지, VMware vCenter 클러스터 및 NetApp Console 요구 사항을 충족하는지 확인하세요.



== 소프트웨어 버전

[cols="35,55a"]
|===
| 요소 | 최소 버전 


| ONTAP 소프트웨어  a| 
ONTAP 9.10.0 이상



| VMware 온프레미스 vCenter  a| 
7.0u3 이상



| AWS용 VMware 클라우드  a| 
사용 가능한 최신 버전



| Amazon FSx for NetApp ONTAP  a| 
사용 가능한 최신 버전

|===


== ONTAP 스토리지 전제 조건

이러한 필수 구성 요소는 NetApp ONTAP 인스턴스의 ONTAP 또는 Amazon FSX에 적용됩니다.

* 소스 클러스터와 대상 클러스터는 피어 관계가 있어야 합니다.
* 재해 복구 볼륨을 호스팅하는 SVM은 대상 클러스터에 있어야 합니다.
* 소스 SVM과 대상 SVM은 피어 관계가 있어야 합니다.
* Amazon FSx for NetApp ONTAP 사용하여 배포하는 경우 다음 필수 조건이 적용됩니다.
+
** VMware DR 데이터 저장소를 호스팅하려면 Amazon FSx for NetApp ONTAP 인스턴스가 VPC에 있어야 합니다. 시작하려면 다음을 참조하세요.link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/getting-started-step1.html["Amazon FSx for ONTAP 설명서"^] .






== VMware vCenter 클러스터 필수 구성 요소

이러한 필수 구성 요소는 온프레미스 vCenter 클러스터와 VMware Cloud for AWS 소프트웨어 정의 데이터 센터(SDDC)에 모두 적용됩니다.

* 검토link:../reference/vcenter-privileges.html["vCenter 권한"] NetApp Disaster Recovery 에 필요합니다.
* NetApp Disaster Recovery 관리하려는 모든 VMware 클러스터는 ONTAP 볼륨을 사용하여 보호하려는 모든 VM을 호스팅합니다.
* NetApp Disaster Recovery 에서 관리하는 모든 VMware 데이터 저장소는 다음 프로토콜 중 하나를 사용해야 합니다.
+
** NFS
** iSCSI 또는 FC 프로토콜을 사용하는 VMFS


* VMware vSphere 버전 7.0 업데이트 3(7.0v3) 이상
* VMware Cloud SDDC를 사용하는 경우 다음 필수 구성 요소가 적용됩니다.
+
** VMware Cloud Console에서 관리자 및 NSX Cloud 관리자 서비스 역할을 사용하세요.  조직 역할에는 조직 소유자도 사용합니다. 참조하다 https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/vmware-cloud-ontap.html["AWS FSx for NetApp ONTAP 설명서와 함께 VMware Cloud Foundations 사용"^] .
** VMware Cloud SDDC를 Amazon FSx for NetApp ONTAP 인스턴스와 연결합니다. 참조하다 https://vmc.techzone.vmware.com/fsx-guide#overview["Amazon FSx for NetApp ONTAP 배포 정보와 AWS의 VMware Cloud 통합"^] .






== NetApp Console 필수 구성 요소



=== NetApp Console 시작하기

아직 하지 않았다면, https://docs.netapp.com/us-en/bluexp-setup-admin/task-sign-up-saas.html["NetApp Console 에 가입하고 조직을 만드세요"^] .



=== ONTAP 및 VMware에 대한 자격 증명 수집

* Amazon FSx for ONTAP 및 AWS 자격 증명은 NetApp Disaster Recovery 관리하는 NetApp Console 프로젝트 내의 시스템에 추가되어야 합니다.
* NetApp Disaster Recovery vCenter 자격 증명이 필요합니다.  NetApp Disaster Recovery 에 사이트를 추가할 때 vCenter 자격 증명을 입력합니다.
+
필요한 vCenter 권한 목록은 다음을 참조하세요.link:../reference/vcenter-privileges.html["NetApp Disaster Recovery 에 필요한 vCenter 권한"] .  사이트를 추가하는 방법에 대한 지침은 다음을 참조하세요.link:../use/sites-add.html["사이트 추가"] .





=== NetApp Console 에이전트 만들기

콘솔 에이전트는 콘솔이 ONTAP 스토리지 및 VMware vCenter 클러스터와 통신할 수 있도록 하는 소프트웨어 구성 요소입니다. 재해 복구가 제대로 작동하려면 이것이 필요합니다. 에이전트는 개인 네트워크(온프레미스 데이터 센터 또는 클라우드 VPC)에 상주하며 ONTAP 스토리지 인스턴스와 추가 서버 및 애플리케이션 구성 요소와 통신합니다. 재해 복구의 경우 이는 관리되는 vCenter 클러스터에 대한 액세스입니다.

NetApp Console 에 콘솔 에이전트를 설정해야 합니다.  에이전트를 사용하면 재해 복구 서비스에 적합한 기능이 포함됩니다.

* NetApp Disaster Recovery 표준 모드 에이전트 배포에서만 작동합니다. 보다 https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-standard-mode.html["표준 모드에서 NetApp Console 시작하기"^] .
* 소스 및 대상 vCenter가 모두 동일한 콘솔 에이전트를 사용하는지 확인하세요.
* 필요한 콘솔 에이전트 유형:
+
** *온프레미스 간 재해 복구*: 재해 복구 사이트에 콘솔 온프레미스 에이전트를 설치합니다.  이 방법을 사용하면 기본 사이트에 장애가 발생해도 서비스가 DR 사이트에서 가상 리소스를 다시 시작하는 것을 방해하지 않습니다. 참조하다 https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html["온프레미스에 콘솔 에이전트 설치 및 설정"^] .
** *온프레미스에서 AWS로*: AWS VPC에 AWS용 콘솔 에이전트를 설치합니다. 참조하다 https://docs.netapp.com/us-en/bluexp-setup-admin/concept-install-options-aws.html["AWS의 콘솔 에이전트 설치 옵션"^] .
+

TIP: 온프레미스 간 연결의 경우 온프레미스 콘솔 에이전트를 사용하세요.  온프레미스에서 AWS로 이동하는 경우 소스 온프레미스 vCenter와 대상 온프레미스 vCenter에 액세스할 수 있는 AWS 콘솔 에이전트를 사용합니다.

** 설치된 콘솔 에이전트는 재해 복구에서 관리할 vCenter 클러스터에서 관리하는 모든 VMware vCenter 클러스터 인스턴스와 ESXi 호스트에 액세스할 수 있어야 합니다.


* NetApp Disaster Recovery 에서 관리할 모든 ONTAP 어레이는 NetApp Disaster Recovery 관리하는 데 사용될 NetApp Console 프로젝트 내의 모든 시스템에 추가되어야 합니다.
+
보다 https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html["온프레미스 ONTAP 클러스터를 찾아보세요"^] .

* NetApp Disaster Recovery 위한 지능형 프록시 설정에 대한 자세한 내용은 다음을 참조하세요.link:../get-started/dr-setup.html["NetApp Disaster Recovery 위한 인프라 설정"] .




== 작업량 전제 조건

애플리케이션 일관성 프로세스가 성공적으로 수행되도록 하려면 다음 전제 조건을 적용하세요.

* 보호할 VM에서 VMware 도구(또는 Open VM 도구)가 실행 중인지 확인하세요.
* Microsoft SQL Server, Oracle Database 또는 둘 다를 실행하는 Windows VM의 경우, 데이터베이스에서 VSS 작성기를 활성화해야 합니다.
* Linux 운영 체제에서 실행되는 Oracle 데이터베이스의 경우 Oracle 데이터베이스 SYSDBA 역할에 대해 운영 체제 사용자 인증이 활성화되어 있어야 합니다.

