---
sidebar: sidebar 
permalink: release-notes/dr-whats-new.html 
keywords: disaster recovery, bluexp, disaster recovery, vmware, vcenter, draas, disaster 
summary: NetApp Disaster Recovery 재해 복구 워크플로를 자동화하는 클라우드 기반 재해 복구 서비스입니다.  VMware용 NetApp Disaster Recovery 사용하면 ONTAP 스토리지를 실행하는 온프레미스 VMware 워크로드를 NetApp 클라우드 스토리지를 사용하여 재해 복구 사이트로 퍼블릭 클라우드의 VMware 소프트웨어 정의 데이터 센터로 복제할 수 있습니다. 
---
= NetApp Disaster Recovery 의 새로운 기능
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp Disaster Recovery 의 새로운 기능을 알아보세요.



== 2025년 10월 6일



=== BlueXP disaster recovery 이제 NetApp Disaster Recovery 입니다.

BlueXP disaster recovery NetApp Disaster Recovery 로 이름이 변경되었습니다.



=== BlueXP 는 이제 NetApp Console 입니다.

강화되고 재구성된 BlueXP 기반을 기반으로 구축된 NetApp Console 엔터프라이즈급 온프레미스 및 클라우드 환경에서 NetApp 스토리지와 NetApp Data Services 중앙에서 관리하여 실시간 통찰력, 더 빠른 워크플로, 간소화된 관리를 제공하며, 높은 보안성과 규정 준수를 보장합니다.

변경된 사항에 대한 자세한 내용은 다음을 참조하세요.link:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["NetApp Console 릴리스 노트"] .



=== 기타 업데이트

* Amazon FSx for NetApp ONTAP 통한 Amazon Elastic VMware Service(EVS) 지원은 공개 미리 보기 단계에 있었습니다. 이번 릴리스를 통해 이제 일반적으로 사용할 수 있게 되었습니다. 자세한 내용은 다음을 참조하세요.link:../reference/evs-deploy-guide-introduction.html["Amazon Elastic VMware Service 및 Amazon FSx for NetApp ONTAP 사용한 NetApp Disaster Recovery 소개"] .
* 온프레미스 배포에 대한 검색 시간 단축을 포함한 스토리지 검색 개선
* 역할 기반 액세스 제어(RBAC) 및 향상된 사용자 권한을 포함한 IAM(Identity and Access Management) 지원
* Azure VMware 솔루션 및 Cloud Volumes ONTAP 에 대한 Private Preview 지원. 이 지원을 통해 이제 Cloud Volumes ONTAP 스토리지를 사용하여 온프레미스에서 Azure VMware 솔루션으로 재해 복구 보호를 구성할 수 있습니다.




== 2025년 8월 4일

버전 4.2.5P2



=== NetApp Disaster Recovery 업데이트

이 릴리스에는 다음과 같은 업데이트가 포함되어 있습니다.

* 여러 스토리지 가상 머신에서 제공되는 동일한 LUN을 처리하기 위해 VMFS 지원이 개선되었습니다.
* 이미 마운트 해제되거나 삭제된 데이터 저장소를 처리하기 위해 테스트 해체 정리를 개선했습니다.
* 제공된 네트워크 내에 입력된 게이트웨이가 포함되어 있는지 확인할 수 있도록 서브넷 매핑이 개선되었습니다.
* VM 이름에 ".com"이 포함되어 있는 경우 복제 계획이 실패할 수 있는 문제를 수정했습니다.
* 복제 계획 생성의 일부로 볼륨을 생성할 때 대상 볼륨이 소스 볼륨과 동일하지 않도록 하는 제한이 제거되었습니다.
* Azure Marketplace에서 NetApp Intelligent Services에 대한 PAYGO(종량제) 구독 지원을 추가하고 무료 평가판 대화 상자에 Azure Marketplace에 대한 링크를 추가했습니다.
+
자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html#licensing["NetApp Disaster Recovery 라이선싱"] 그리고 https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html["NetApp Disaster Recovery 에 대한 라이선싱 설정"] .





== 2025년 7월 14일

버전 4.2.5



=== NetApp Disaster Recovery 의 사용자 역할

NetApp Disaster Recovery 이제 각 사용자가 특정 기능과 작업에 대해 갖는 액세스를 관리하는 역할을 사용합니다.

이 서비스는 NetApp Disaster Recovery 에 특정한 다음 역할을 사용합니다.

* *재해 복구 관리자*: NetApp Disaster Recovery 에서 모든 작업을 수행합니다.
* *재해 복구 장애 조치 관리자*: NetApp Disaster Recovery 에서 장애 조치 및 마이그레이션 작업을 수행합니다.
* *재해 복구 애플리케이션 관리자*: 복제 계획을 만들고 수정하고 테스트 장애 조치를 시작합니다.
* *재해 복구 뷰어*: NetApp Disaster Recovery 에서 정보를 볼 수 있지만, 어떤 작업도 수행할 수 없습니다.


NetApp Disaster Recovery 서비스를 클릭하고 처음으로 구성하는 경우 *SnapCenterAdmin* 권한이나 *조직 관리자* 역할이 있어야 합니다.

자세한 내용은 다음을 참조하십시오.  https://docs.netapp.com/us-en/bluexp-disaster-recovery/reference/dr-reference-roles.html["NetApp Disaster Recovery 의 사용자 역할 및 권한"] .

https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["모든 서비스에 대한 액세스 역할에 대해 알아보세요"^] .



=== NetApp Disaster Recovery 의 기타 업데이트

* 향상된 네트워크 검색
* 확장성 개선:
+
** 모든 세부 정보 대신 필요한 메타데이터만 필터링
** VM 리소스를 더 빠르게 검색하고 업데이트하기 위한 검색 개선
** 데이터 검색 및 데이터 업데이트를 위한 메모리 최적화 및 성능 최적화
** vCenter SDK 클라이언트 생성 및 풀 관리 개선


* 다음 예약 또는 수동 검색 시 오래된 데이터 관리:
+
** vCenter에서 VM이 삭제되면 이제 NetApp Disaster Recovery 복제 계획에서 자동으로 해당 VM을 제거합니다.
** vCenter에서 데이터 저장소나 네트워크가 삭제되면 이제 NetApp Disaster Recovery 복제 계획 및 리소스 그룹에서도 해당 데이터 저장소나 네트워크를 삭제합니다.
** vCenter에서 클러스터, 호스트 또는 데이터 센터가 삭제되면 이제 NetApp Disaster Recovery 복제 계획 및 리소스 그룹에서 해당 항목을 삭제합니다.


* 이제 브라우저의 시크릿 모드에서도 Swagger 문서에 액세스할 수 있습니다. NetApp Disaster Recovery 에서 설정 옵션 > API 설명서를 통해 액세스할 수 있으며, 브라우저의 시크릿 모드에서 다음 URL을 통해 직접 액세스할 수도 있습니다. https://snapcenter.cloudmanager.cloud.netapp.com/api/api-doc/draas["Swagger 문서"^] .
* 어떤 상황에서는 장애 복구 작업 후 작업이 완료된 후에도 iGroup이 남겨지는 경우가 있었습니다. 이 업데이트는 오래된 iGroup을 제거합니다.
* 복제 계획에 NFS FQDN이 사용된 경우 NetApp Disaster Recovery 이제 이를 IP 주소로 확인합니다. 이 업데이트는 재해 복구 사이트에서 FQDN을 확인할 수 없는 경우에 유용합니다.
* UI 정렬 개선
* 성공적인 검색 후 vCenter 크기 조정 세부 정보를 캡처하기 위한 로그 개선




== 2025년 6월 30일

버전 4.2.4P2



=== 발견 개선

이 업데이트는 검색 프로세스를 개선하여 검색에 필요한 시간을 줄여줍니다.



== 2025년 6월 23일

버전 4.2.4P1



=== 서브넷 매핑 개선

이 업데이트에서는 새로운 검색 기능을 통해 서브넷 매핑 추가 및 편집 대화 상자가 개선되었습니다.  이제 검색어를 입력하여 특정 서브넷을 빠르게 찾을 수 있어 서브넷 매핑을 더 쉽게 관리할 수 있습니다.



== 2025년 6월 9일

버전 4.2.4



=== Windows 로컬 관리자 암호 솔루션(LAPS) 지원

Windows 로컬 관리자 암호 솔루션(Windows LAPS)은 Active Directory에서 로컬 관리자 계정의 암호를 자동으로 관리하고 백업하는 Windows 기능입니다.

이제 도메인 컨트롤러 세부 정보를 제공하여 서브넷 매핑 옵션을 선택하고 LAPS 옵션을 확인할 수 있습니다.  이 옵션을 사용하면 각 가상 머신에 대한 비밀번호를 제공할 필요가 없습니다.

자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획 만들기"] .



== 2025년 5월 13일

버전 4.2.3



=== 서브넷 매핑

이 릴리스에서는 서브넷 매핑을 사용하여 새로운 방식으로 장애 조치 시 IP 주소를 관리할 수 있으며, 이를 통해 각 vCenter에 대한 서브넷을 추가할 수 있습니다.  이렇게 하면 각 가상 네트워크에 대한 IPv4 CIDR, 기본 게이트웨이, DNS가 정의됩니다.

장애 조치 시 NetApp Disaster Recovery 매핑된 가상 네트워크에 제공된 CIDR을 보고 각 vNIC의 적절한 IP 주소를 결정하고 이를 사용하여 새 IP 주소를 파생합니다.

예를 들어:

* 네트워크A = 10.1.1.0/24
* 네트워크B = 192.168.1.0/24


VM1에는 NetworkA에 연결된 vNIC(10.1.1.50)가 있습니다.  NetworkA는 복제 계획 설정에서 NetworkB에 매핑됩니다.

장애 조치 시 NetApp Disaster Recovery 원래 IP 주소(10.1.1)의 네트워크 부분을 대체하고 원래 IP 주소(10.1.1.50)의 호스트 주소(.50)를 유지합니다.  VM1의 경우 NetApp Disaster Recovery NetworkB의 CIDR 설정을 살펴보고 NetworkB의 네트워크 부분인 192.168.1을 사용하고 호스트 부분(.50)은 그대로 유지하여 VM1의 새 IP 주소를 생성합니다.  새로운 IP는 192.168.1.50이 됩니다.

요약하자면, 호스트 주소는 동일하게 유지되지만 네트워크 주소는 사이트 서브넷 매핑에 구성된 주소로 대체됩니다.  이를 통해 장애 조치 시 IP 주소 재할당을 보다 쉽게 관리할 수 있으며, 특히 관리해야 할 네트워크가 수백 개이고 VM이 수천 개일 경우 더욱 그렇습니다.

사이트에 서브넷 매핑을 포함하는 방법에 대한 자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/sites-add.html["vCenter 서버 사이트 추가"] .



=== 스킵 보호

이제 복제 계획 장애 조치 후 서비스가 자동으로 역방향 보호 관계를 생성하지 않도록 보호를 건너뛸 수 있습니다.  NetApp Disaster Recovery 에서 다시 온라인으로 전환하기 전에 복원된 사이트에서 추가 작업을 수행하려는 경우 이 기능이 유용합니다.

장애 조치를 시작하면 기본적으로 서비스는 복제 계획의 각 볼륨에 대해 역방향 보호 관계를 자동으로 생성합니다(원본 소스 사이트가 온라인 상태인 경우).  즉, 서비스는 대상 사이트에서 소스 사이트로 SnapMirror 관계를 생성합니다.  또한 이 서비스는 장애 복구를 시작하면 SnapMirror 관계를 자동으로 되돌립니다.

장애 조치를 시작할 때 이제 *보호 건너뛰기* 옵션을 선택할 수 있습니다.  이를 통해 서비스는 SnapMirror 관계를 자동으로 반전시키지 않습니다.  대신 복제 계획의 양쪽에 쓰기 가능한 볼륨이 남습니다.

원래 소스 사이트가 다시 온라인 상태가 되면 복제 계획 작업 메뉴에서 *리소스 보호*를 선택하여 역방향 보호를 설정할 수 있습니다.  이는 계획의 각 볼륨에 대해 역방향 복제 관계를 생성하려고 시도합니다.  보호가 복구될 때까지 이 작업을 반복해서 실행할 수 있습니다.  보호가 복구되면 평소와 같은 방식으로 장애 복구를 시작할 수 있습니다.

자세한 내용은 건너뛰기 보호에 대한 내용을 참조하세요. https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["원격 사이트로 애플리케이션 장애 조치"] .



=== SnapMirror 복제 계획에서 업데이트를 일정에 추가합니다.

NetApp Disaster Recovery 이제 기본 ONTAP SnapMirror 정책 스케줄러나 ONTAP 과의 타사 통합과 같은 외부 스냅샷 관리 솔루션을 사용할 수 있도록 지원합니다.  복제 계획의 모든 데이터 저장소(볼륨)에 이미 다른 곳에서 관리되는 SnapMirror 관계가 있는 경우 NetApp Disaster Recovery 에서 해당 스냅샷을 복구 지점으로 사용할 수 있습니다.

구성하려면 복제 계획 > 리소스 매핑 섹션에서 데이터 저장소 매핑을 구성할 때 *플랫폼 관리 백업 및 보존 일정 사용* 확인란을 선택합니다.

해당 옵션을 선택하면 NetApp Disaster Recovery 백업 일정을 구성하지 않습니다.  그러나 테스트, 장애 조치, 장애 복구 작업을 위해 스냅샷이 계속 생성될 수 있으므로 보존 일정을 구성해야 합니다.

이것이 구성된 후에는 서비스가 정기적으로 예약된 스냅샷을 찍지 않고 대신 외부 엔터티를 사용하여 해당 스냅샷을 찍고 업데이트합니다.

복제 계획에서 외부 스냅샷 솔루션을 사용하는 방법에 대한 자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획 만들기"] .



== 2025년 4월 16일

버전 4.2.2



=== VM에 대한 예약된 검색

NetApp Disaster Recovery 24시간마다 검색을 수행합니다.  이번 릴리스를 통해 이제 필요에 맞게 검색 일정을 사용자 지정하고 필요할 때 성능에 미치는 영향을 줄일 수 있습니다.  예를 들어, VM 수가 많은 경우 검색 일정을 48시간마다 실행되도록 설정할 수 있습니다.  VM 수가 적은 경우 검색 일정을 12시간마다 실행되도록 설정할 수 있습니다.

검색 일정을 예약하고 싶지 않으면 예약된 검색 옵션을 비활성화하고 언제든지 수동으로 검색을 새로 고칠 수 있습니다.

자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/sites-add.html["vCenter 서버 사이트 추가"] .



=== 리소스 그룹 데이터 저장소 지원

이전에는 VM별로만 리소스 그룹을 만들 수 있었습니다.  이 릴리스에서는 데이터 저장소별로 리소스 그룹을 만들 수 있습니다.  복제 계획을 만들고 해당 계획에 대한 리소스 그룹을 만들면 데이터 저장소의 모든 VM이 나열됩니다.  이 기능은 다수의 VM이 있고 이를 데이터 저장소별로 그룹화하려는 경우에 유용합니다.

다음과 같은 방법으로 데이터 저장소를 사용하여 리소스 그룹을 만들 수 있습니다.

* 데이터 저장소를 사용하여 리소스 그룹을 추가하는 경우 데이터 저장소 목록을 볼 수 있습니다.  하나 이상의 데이터 저장소를 선택하여 리소스 그룹을 만들 수 있습니다.
* 복제 계획을 만들고 계획 내에서 리소스 그룹을 만들면 데이터 저장소에서 VM을 볼 수 있습니다.


자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획 만들기"] .



=== 무료 체험판 또는 라이센스 만료 알림

이 릴리스에서는 무료 평가판이 60일 후에 만료된다는 알림을 제공하여 라이선스를 받을 시간을 확보할 수 있도록 합니다.  이 릴리스에서는 라이센스가 만료되는 날에 대한 알림도 제공합니다.



=== 서비스 업데이트 알림

이번 릴리스에서는 서비스가 업그레이드되고 서비스가 유지 관리 모드로 전환되었음을 나타내는 배너가 상단에 나타납니다.  배너는 서비스가 업그레이드될 때 나타나고 업그레이드가 완료되면 사라집니다.  업그레이드가 진행되는 동안 UI에서 작업을 계속할 수 있지만 새로운 작업을 제출할 수는 없습니다.  업데이트가 완료되고 서비스가 프로덕션 모드로 돌아온 후에 예약된 작업이 실행됩니다.



== 2025년 3월 10일

버전 4.2.1



=== 지능형 프록시 지원

NetApp Console 에이전트는 지능형 프록시를 지원합니다.  지능형 프록시는 온프레미스 시스템을 NetApp Disaster Recovery 에 연결하는 가볍고 안전하며 효율적인 방법입니다.  VPN이나 ​​직접 인터넷 접속이 필요 없이 시스템과 NetApp Disaster Recovery 간의 안전한 연결을 제공합니다.  이 최적화된 프록시 구현은 로컬 네트워크 내의 API 트래픽을 오프로드합니다.

프록시가 구성되면 NetApp Disaster Recovery VMware 또는 ONTAP 과 직접 통신을 시도하고 직접 통신이 실패하면 구성된 프록시를 사용합니다.

NetApp Disaster Recovery 프록시 구현에는 HTTPS 프로토콜을 사용하여 콘솔 에이전트와 모든 vCenter 서버 및 ONTAP 어레이 간에 포트 443 통신이 필요합니다.  콘솔 에이전트 내의 NetApp Disaster Recovery 에이전트는 모든 작업을 수행할 때 VMware vSphere, VC 또는 ONTAP 과 직접 통신합니다.

NetApp Disaster Recovery 용 지능형 프록시에 대한 자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-setup.html["NetApp Disaster Recovery 위한 인프라 설정"] .

NetApp Console 에서 일반 프록시 설정에 대한 자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/bluexp-setup-admin/task-configuring-proxy.html["프록시 서버를 사용하도록 콘솔 에이전트 구성"^] .



=== 언제든지 무료 체험을 종료하세요

언제든지 무료 체험을 중단할 수 있으며, 체험 기간이 만료될 때까지 기다릴 수도 있습니다.

보다 https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html#end-the-free-trial["무료 체험 종료"] .



== 2025년 2월 19일

버전 4.2



=== VMFS 스토리지의 VM 및 데이터 저장소에 대한 ASA r2 지원

NetApp Disaster Recovery 의 이 릴리스에서는 VMFS 스토리지의 VM 및 데이터 저장소에 대한 ASA r2에 대한 지원을 제공합니다.  ASA r2 시스템에서 ONTAP 소프트웨어는 SAN 환경에서 지원되지 않는 기능을 제거하는 동시에 필수적인 SAN 기능을 지원합니다.

이 릴리스는 ASA r2에 대해 다음 기능을 지원합니다.

* 기본 스토리지에 대한 일관성 그룹 프로비저닝(계층 구조 없이 단일 레벨만 있는 플랫 일관성 그룹만 해당)
* SnapMirror 자동화를 포함한 백업(일관성 그룹) 작업


NetApp Disaster Recovery 에서 ASA r2를 지원하려면 ONTAP 9.16.1이 필요합니다.

데이터 저장소는 ONTAP 볼륨이나 ASA r2 스토리지 유닛에 마운트할 수 있지만 NetApp Disaster Recovery 의 리소스 그룹에는 ONTAP 의 데이터 저장소와 ASA r2의 데이터 저장소를 모두 포함할 수 없습니다.  리소스 그룹에서 ONTAP 의 데이터 저장소나 ASA r2의 데이터 저장소를 선택할 수 있습니다.



== 2024년 10월 30일



=== 보고

이제 풍경을 분석하는 데 도움이 되는 보고서를 생성하고 다운로드할 수 있습니다.  사전 설계된 보고서는 장애 조치(failover)와 장애 복구(failback)를 요약하고, 모든 사이트의 복제 세부 정보를 표시하며, 지난 7일간의 작업 세부 정보를 표시합니다.

참조하다 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/reports.html["재해 복구 보고서 만들기"] .



=== 30일 무료 체험

이제 NetApp Disaster Recovery 의 30일 무료 평가판에 등록할 수 있습니다.  이전에는 무료 체험 기간이 90일이었습니다.

참조하다 https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html["라이센스 설정"] .



=== 복제 계획 비활성화 및 활성화

이전 릴리스에는 일일 및 주간 일정을 지원하는 데 필요한 장애 조치 테스트 일정 구조에 대한 업데이트가 포함되었습니다.  이 업데이트를 적용하려면 새로운 일일 및 주간 장애 조치 테스트 일정을 사용할 수 있도록 모든 기존 복제 계획을 비활성화했다가 다시 활성화해야 합니다.  이는 일회성 요구 사항입니다.

방법은 다음과 같습니다.

. 메뉴에서 *복제 계획*을 선택합니다.
. 계획을 선택하고 작업 아이콘을 선택하여 드롭다운 메뉴를 표시합니다.
. *비활성화*를 선택하세요.
. 몇 분 후에 *활성화*를 선택하세요.




=== 폴더 매핑

복제 계획을 생성하고 컴퓨팅 리소스를 매핑할 때 이제 폴더를 매핑하여 데이터 센터, 클러스터 및 호스트에 대해 지정한 폴더에 VM을 복구할 수 있습니다.

자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획 만들기"] .



=== 장애 조치, 장애 복구 및 테스트 장애 조치에 사용할 수 있는 VM 세부 정보

장애가 발생하고 장애 조치를 시작하거나, 장애 복구를 수행하거나, 장애 조치를 테스트하는 경우 이제 VM의 세부 정보를 확인하고 다시 시작되지 않은 VM을 식별할 수 있습니다.

참조하다 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["원격 사이트로 애플리케이션 장애 조치"] .



=== 순서가 지정된 부팅 시퀀스를 사용한 VM 부팅 지연

복제 계획을 만들 때 이제 계획에 있는 각 VM에 대한 부팅 지연을 설정할 수 있습니다.  이를 통해 VM이 시작될 순서를 설정하여 후속 우선순위 VM이 시작되기 전에 모든 우선순위 1 VM이 실행되도록 할 수 있습니다.

자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획 만들기"] .



=== VM 운영 체제 정보

복제 계획을 만들면 이제 계획에 있는 각 VM의 운영 체제를 볼 수 있습니다.  이는 리소스 그룹에서 VM을 어떻게 그룹화할지 결정하는 데 유용합니다.

자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획 만들기"] .



=== VM 이름 별칭

복제 계획을 만들 때 이제 재해 복구 사이트의 VM 이름에 접두사와 접미사를 추가할 수 있습니다.  이를 통해 계획에 있는 VM에 대해 보다 설명적인 이름을 사용할 수 있습니다.

자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획 만들기"] .



=== 오래된 스냅샷 정리

지정한 보존 기간을 넘어서 더 이상 필요하지 않은 스냅샷은 삭제할 수 있습니다.  스냅샷 보존 횟수를 줄이면 시간이 지남에 따라 스냅샷이 누적될 수 있으며, 이제 스냅샷을 제거하여 공간을 확보할 수 있습니다.  이 작업은 언제든지 필요할 때 수행할 수 있으며, 복제 계획을 삭제할 때도 수행할 수 있습니다.

자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["사이트, 리소스 그룹, 복제 계획, 데이터 저장소 및 가상 머신 정보를 관리합니다."] .



=== 스냅샷 조정

이제 소스와 대상 간에 동기화되지 않은 스냅샷을 조정할 수 있습니다.  이는 NetApp Disaster Recovery 외부의 대상에서 스냅샷이 삭제된 경우 발생할 수 있습니다.  이 서비스는 24시간마다 소스의 스냅샷을 자동으로 삭제합니다.  하지만 필요에 따라 이를 수행할 수도 있습니다.  이 기능을 사용하면 모든 사이트에서 스냅샷이 일관성을 유지하도록 할 수 있습니다.

자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["복제 계획 관리"] .



== 2024년 9월 20일



=== 온프레미스 간 VMware VMFS 데이터 저장소 지원

이 릴리스에는 온프레미스 스토리지로 보호되는 iSCSI 및 FC를 위한 VMware vSphere 가상 머신 파일 시스템(VMFS) 데이터 저장소에 마운트된 VM에 대한 지원이 포함됩니다.  이전에는 이 서비스에서 iSCSI 및 FC에 대한 VMFS 데이터 저장소를 지원하는 _기술 미리보기_가 제공되었습니다.

iSCSI 및 FC 프로토콜과 관련된 추가 고려 사항은 다음과 같습니다.

* FC 지원은 복제가 아닌 클라이언트 프런트엔드 프로토콜을 위한 것입니다.
* NetApp Disaster Recovery ONTAP 볼륨당 하나의 LUN만 지원합니다.  볼륨에는 여러 개의 LUN이 있어서는 안 됩니다.
* 모든 복제 계획의 경우 대상 ONTAP 볼륨은 보호된 VM을 호스팅하는 소스 ONTAP 볼륨과 동일한 프로토콜을 사용해야 합니다.  예를 들어, 소스가 FC 프로토콜을 사용하는 경우 대상도 FC를 사용해야 합니다.




== 2024년 8월 2일



=== FC용 온프레미스 간 VMware VMFS 데이터 저장소 지원

이 릴리스에는 FC로 보호되는 온프레미스 스토리지를 위한 VMware vSphere 가상 머신 파일 시스템(VMFS) 데이터 저장소에 마운트된 VM에 대한 지원에 대한 _기술 미리보기_가 포함되어 있습니다.  이전에는 이 서비스에서 iSCSI용 VMFS 데이터 저장소를 지원하는 기술 미리보기가 제공되었습니다.


NOTE: NetApp 미리 본 워크로드 용량에 대해 요금을 청구하지 않습니다.



=== 작업 취소

이 릴리스에서는 이제 Job Monitor UI에서 작업을 취소할 수 있습니다.

참조하다 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/monitor-jobs.html["작업 모니터링"] .



== 2024년 7월 17일



=== 장애 조치 테스트 일정

이 릴리스에는 일일 및 주간 일정을 지원하는 데 필요한 장애 조치 테스트 일정 구조에 대한 업데이트가 포함되어 있습니다.  이 업데이트를 적용하려면 새로운 일일 및 주간 장애 조치 테스트 일정을 사용할 수 있도록 모든 기존 복제 계획을 비활성화했다가 다시 활성화해야 합니다.  이는 일회성 요구 사항입니다.

방법은 다음과 같습니다.

. 메뉴에서 *복제 계획*을 선택합니다.
. 계획을 선택하고 작업 아이콘을 선택하여 드롭다운 메뉴를 표시합니다.
. *비활성화*를 선택하세요.
. 몇 분 후에 *활성화*를 선택하세요.




=== 복제 계획 업데이트

이 릴리스에는 복제 계획 데이터에 대한 업데이트가 포함되어 있어 "스냅샷을 찾을 수 없음" 문제가 해결되었습니다.  이렇게 하려면 모든 복제 계획에서 보존 횟수를 1로 변경하고 주문형 스냅샷을 시작해야 합니다.  이 프로세스는 새로운 백업을 만들고 이전 백업을 모두 제거합니다.

방법은 다음과 같습니다.

. 메뉴에서 *복제 계획*을 선택합니다.
. 복제 계획을 선택하고, *장애 조치 매핑* 탭을 선택한 다음, *편집* 연필 아이콘을 선택합니다.
. *데이터 저장소* 화살표를 선택하여 확장합니다.
. 복제 계획에서 보존 횟수 값을 확인하세요. 이러한 단계를 완료한 후에는 원래 값을 다시 설정해야 합니다.
. 카운트를 1로 줄이세요.
. 주문형 스냅샷을 시작합니다. 이렇게 하려면 복제 계획 페이지에서 계획을 선택하고 작업 아이콘을 선택한 다음 *지금 스냅샷 찍기*를 선택합니다.
. 스냅샷 작업이 성공적으로 완료되면 복제 계획의 개수를 첫 번째 단계에서 기록한 원래 값으로 다시 늘립니다.
. 기존의 모든 복제 계획에 대해 이 단계를 반복합니다.




== 2024년 7월 5일

이 NetApp Disaster Recovery 릴리스에는 다음과 같은 업데이트가 포함되어 있습니다.



=== AFF A 시리즈 지원

이 릴리스는 NetApp AFF A 시리즈 하드웨어 플랫폼을 지원합니다.



=== 온프레미스 간 VMware VMFS 데이터 저장소 지원

이 릴리스에는 온프레미스 스토리지로 보호되는 VMware vSphere 가상 머신 파일 시스템(VMFS) 데이터 저장소에 마운트된 VM에 대한 지원에 대한 _기술 미리보기_가 포함되어 있습니다.  이 릴리스에서는 온프레미스 VMware 워크로드에서 VMFS 데이터 저장소가 있는 온프레미스 VMware 환경으로의 재해 복구가 기술 미리 보기에서 지원됩니다.


NOTE: NetApp 미리 본 워크로드 용량에 대해 요금을 청구하지 않습니다.



=== 복제 계획 업데이트

애플리케이션 페이지에서 데이터 저장소별로 VM을 필터링하고 리소스 매핑 페이지에서 추가 대상 세부 정보를 선택하면 복제 계획을 더 쉽게 추가할 수 있습니다. 참조하다 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획 만들기"] .



=== 복제 계획 편집

이번 릴리스에서는 장애 조치 매핑 페이지가 개선되어 명확성이 향상되었습니다.

참조하다 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["계획 관리"] .



=== VM 편집

이번 릴리스에서는 계획에서 VM을 편집하는 프로세스에 몇 가지 사소한 UI 개선 사항이 포함되었습니다.

참조하다 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["VM 관리"] .



=== 업데이트 장애 조치

장애 조치를 시작하기 전에 이제 VM의 상태와 전원이 켜져 있는지 꺼져 있는지 확인할 수 있습니다.  이제 장애 조치 프로세스를 통해 지금 스냅샷을 찍거나 스냅샷을 선택할 수 있습니다.

참조하다 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["원격 사이트로 애플리케이션 장애 조치"] .



=== 장애 조치 테스트 일정

이제 장애 조치 테스트를 편집하고 장애 조치 테스트에 대한 일일, 주간, 월간 일정을 설정할 수 있습니다.

참조하다 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["계획 관리"] .



=== 필수 정보 업데이트

NetApp Disaster Recovery 필수 구성 요소 정보가 업데이트되었습니다.

참조하다 https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-prerequisites.html["NetApp Disaster Recovery 필수 구성 요소"] .



== 2024년 5월 15일

이 NetApp Disaster Recovery 릴리스에는 다음과 같은 업데이트가 포함되어 있습니다.



=== 온프레미스에서 온프레미스로 VMware 워크로드 복제

이 기능은 이제 일반 공급 기능으로 출시되었습니다.  이전에는 기능이 제한된 기술 미리보기였습니다.



=== 라이센스 업데이트

NetApp Disaster Recovery 사용하면 90일 무료 평가판에 가입하거나 Amazon Marketplace에서 사용량에 따라 지불하는(PAYGO) 구독을 구매하거나 NetApp 영업 담당자나 NetApp 지원 사이트(NSS)에서 얻을 수 있는 NetApp 라이선스 파일(NLF)인 Bring Your Own License(BYOL)를 사용할 수 있습니다.

NetApp Disaster Recovery 에 대한 라이선싱 설정에 대한 자세한 내용은 다음을 참조하세요.link:../get-started/dr-licensing.html["라이센스 설정"] .

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["NetApp Disaster Recovery 에 대해 자세히 알아보세요"] .



== 2024년 3월 5일

이는 NetApp Disaster Recovery 의 일반 공급 릴리스로, 다음 업데이트가 포함되어 있습니다.



=== 라이센스 업데이트

NetApp Disaster Recovery 사용하면 90일 무료 평가판에 가입하거나 NetApp 영업 담당자로부터 받는 NetApp 라이선스 파일(NLF)인 BYOL(Bring Your Own License)을 사용할 수 있습니다.  NetApp Console 구독에서 BYOL을 활성화하려면 라이선스 일련 번호를 사용할 수 있습니다.  NetApp Disaster Recovery 요금은 데이터 저장소의 프로비저닝된 용량을 기준으로 합니다.

NetApp Disaster Recovery 에 대한 라이선싱 설정에 대한 자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html["라이센스 설정"] .

*모든* NetApp Console 데이터 서비스에 대한 라이선스 관리에 대한 자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-data-services-licenses.html["모든 NetApp Console 데이터 서비스에 대한 라이선스 관리"^] .



=== 일정 편집

이 릴리스를 사용하면 규정 준수 및 장애 조치 테스트를 위한 일정을 설정하여 필요할 경우 해당 테스트가 올바르게 작동하는지 확인할 수 있습니다.

자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획 만들기"] .



== 2024년 2월 1일

이 NetApp Disaster Recovery 미리 보기 릴리스에는 다음과 같은 업데이트가 포함되어 있습니다.



=== 네트워크 강화

이 릴리스에서는 이제 VM CPU 및 RAM 값의 크기를 조정할 수 있습니다.  이제 VM에 대한 네트워크 DHCP 또는 정적 IP 주소를 선택할 수도 있습니다.

* DHCP: 이 옵션을 선택하면 VM에 대한 자격 증명을 제공합니다.
* 고정 IP: 소스 VM에서 동일하거나 다른 정보를 선택할 수 있습니다.  출처와 동일한 것을 선택하면 자격 증명을 입력할 필요가 없습니다.  반면, 소스의 다른 정보를 사용하기로 선택한 경우 자격 증명, IP 주소, 서브넷 마스크, DNS 및 게이트웨이 정보를 제공할 수 있습니다.


자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획 만들기"] .



=== 사용자 정의 스크립트

이제 장애 조치 후 프로세스에 포함될 수 있습니다.  사용자 정의 스크립트를 사용하면 장애 조치 프로세스 후에 NetApp Disaster Recovery 스크립트를 실행하도록 할 수 있습니다.  예를 들어, 장애 조치가 완료된 후 사용자 정의 스크립트를 사용하여 모든 데이터베이스 트랜잭션을 재개할 수 있습니다.

자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["원격 사이트로 장애 조치"] .



=== SnapMirror 관계

이제 복제 계획을 개발하는 동안 SnapMirror 관계를 만들 수 있습니다.  이전에는 NetApp Disaster Recovery 외부에서 관계를 만들어야 했습니다.

자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획 만들기"] .



=== 일관성 그룹

복제 계획을 만들 때 서로 다른 볼륨과 서로 다른 SVM에 속한 VM을 포함할 수 있습니다.  NetApp Disaster Recovery 모든 볼륨을 포함하여 일관성 그룹 스냅샷을 만들고 모든 보조 위치를 업데이트합니다.

자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획 만들기"] .



=== VM 전원 켜짐 지연 옵션

복제 계획을 만들 때 리소스 그룹에 VM을 추가할 수 있습니다.  리소스 그룹을 사용하면 각 VM에 지연 시간을 설정하여 지연된 순서로 전원이 켜지도록 할 수 있습니다.

자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획 만들기"] .



=== 애플리케이션 일관성 스냅샷 복사본

애플리케이션과 일관된 스냅샷 복사본을 생성하도록 지정할 수 있습니다.  이 서비스는 애플리케이션을 정지시킨 다음 스냅샷을 찍어 애플리케이션의 일관된 상태를 얻습니다.

자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획 만들기"] .



== 2024년 1월 11일

NetApp Disaster Recovery 의 이 미리 보기 릴리스에는 다음과 같은 업데이트가 포함되어 있습니다.



=== 대시보드를 더 빠르게

이번 릴리스를 통해 대시보드의 다른 페이지에 있는 정보에 더 빠르게 액세스할 수 있습니다.

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["NetApp Disaster Recovery 에 대해 알아보세요"] .



== 2023년 10월 20일

NetApp Disaster Recovery 의 이 미리 보기 릴리스에는 다음과 같은 업데이트가 포함되어 있습니다.



=== 온프레미스 NFS 기반 VMware 워크로드 보호

이제 NetApp Disaster Recovery 사용하면 퍼블릭 클라우드뿐만 아니라 온프레미스 NFS 기반 VMware 환경의 재해로부터 온프레미스 NFS 기반 VMware 워크로드를 보호할 수 있습니다.  NetApp Disaster Recovery 재해 복구 계획의 완료를 조율합니다.


NOTE: 이 미리보기 제공을 통해 NetApp 일반 공급 전에 제공 세부 정보, 내용 및 일정을 수정할 권리가 있습니다.

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["NetApp Disaster Recovery 에 대해 자세히 알아보세요"] .



== 2023년 9월 27일

NetApp Disaster Recovery 의 이 미리 보기 릴리스에는 다음과 같은 업데이트가 포함되어 있습니다.



=== 대시보드 업데이트

이제 대시보드에서 옵션을 선택하여 정보를 더 빠르고 쉽게 검토할 수 있습니다. 또한 대시보드에는 이제 장애 조치 및 마이그레이션 상태가 표시됩니다.

참조하다 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/dashboard-view.html["대시보드에서 재해 복구 계획의 상태를 확인하세요."] .



=== 복제 계획 업데이트

* *RPO*: 이제 복제 계획의 데이터 저장소 섹션에 복구 지점 목표(RPO)와 보존 횟수를 입력할 수 있습니다. 이는 설정된 시간보다 오래되지 않은 데이터의 양을 나타냅니다. 예를 들어, 5분으로 설정하면 비즈니스에 중요한 요구 사항에 영향을 미치지 않고도 재해가 발생해도 시스템은 최대 5분 동안의 데이터를 잃을 수 있습니다.
+
참조하다 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획 만들기"] .

* *네트워킹 향상*: 복제 계획의 가상 머신 섹션에서 소스와 대상 위치 간의 네트워킹을 매핑할 때 NetApp Disaster Recovery 이제 DHCP 또는 정적 IP의 두 가지 옵션을 제공합니다. 이전에는 DHCP만 지원되었습니다. 고정 IP의 경우 서브넷, 게이트웨이, DNS 서버를 구성합니다. 또한 이제 가상 머신에 대한 자격 증명을 입력할 수 있습니다.
+
참조하다 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획 만들기"] .

* *일정 편집*: 이제 복제 계획 일정을 업데이트할 수 있습니다.
+
참조하다 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["리소스 관리"] .

* * SnapMirror 자동화*: 이 릴리스에서 복제 계획을 생성하는 동안 다음 구성 중 하나로 소스 볼륨과 대상 볼륨 간의 SnapMirror 관계를 정의할 수 있습니다.
+
** 1에서 1까지
** 팬아웃 아키텍처의 1대다
** 일관성 그룹으로서 다수 대 1
** 다대다
+
참조하다 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획 만들기"] .







== 2023년 8월 1일



=== NetApp Disaster Recovery 미리보기

NetApp Disaster Recovery 미리보기는 재해 복구 워크플로를 자동화하는 클라우드 기반 재해 복구 서비스입니다.  NetApp Disaster Recovery 미리 보기를 사용하면 Amazon FSx for ONTAP 을 사용하여 AWS의 VMware Cloud(VMC)에서 NetApp 스토리지를 실행하는 온프레미스 NFS 기반 VMware 워크로드를 보호할 수 있습니다.


NOTE: 이 미리보기 제공을 통해 NetApp 일반 공급 전에 제공 세부 정보, 내용 및 일정을 수정할 권리가 있습니다.

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["NetApp Disaster Recovery 에 대해 자세히 알아보세요"] .

이 릴리스에는 다음과 같은 업데이트가 포함되어 있습니다.



=== 부팅 순서에 대한 리소스 그룹 업데이트

재해 복구 또는 복제 계획을 만들 때 가상 머신을 기능적 리소스 그룹에 추가할 수 있습니다. 리소스 그룹을 사용하면 요구 사항을 충족하는 논리적 그룹에 종속된 가상 머신 세트를 넣을 수 있습니다. 예를 들어, 그룹에는 복구 시 실행할 수 있는 부팅 순서가 포함될 수 있습니다. 이 릴리스에서는 각 리소스 그룹에 하나 이상의 가상 머신을 포함할 수 있습니다. 가상 머신은 계획에 포함한 순서에 따라 전원이 켜집니다. 참조하다 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html#select-applications-to-replicate-and-assign-resource-groups["복제할 애플리케이션을 선택하고 리소스 그룹을 할당합니다."] .



=== 복제 검증

재해 복구 또는 복제 계획을 만들고 마법사에서 재발을 식별하고 재해 복구 사이트로 복제를 시작하면 30분마다 NetApp Disaster Recovery 복제가 실제로 계획에 따라 발생하는지 확인합니다. 작업 모니터 페이지에서 진행 상황을 모니터링할 수 있습니다.  https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/replicate.html["다른 사이트에 애플리케이션 복제"] .



=== 복제 계획은 RPO(복구 지점 목표) 전송 일정을 보여줍니다.

재해 복구 또는 복제 계획을 만들 때 VM을 선택합니다. 이 릴리스에서는 이제 데이터 저장소 또는 VM에 연결된 각 볼륨과 연관된 SnapMirror 볼 수 있습니다. SnapMirror 일정과 연결된 RPO 전송 일정도 볼 수 있습니다. RPO는 재해 발생 후 복구에 백업 일정이 충분한지 여부를 판단하는 데 도움이 됩니다. 참조하다 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["복제 계획 만들기"] .



=== 작업 모니터 업데이트

이제 작업 모니터 페이지에 새로 고침 옵션이 포함되어 작업의 최신 상태를 확인할 수 있습니다.  https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/monitor-jobs.html["재해 복구 작업 모니터링"] .



== 2023년 5월 18일

이는 NetApp Disaster Recovery 의 최초 릴리스입니다.



=== 클라우드 기반 재해 복구 서비스

NetApp Disaster Recovery 재해 복구 워크플로를 자동화하는 클라우드 기반 재해 복구 서비스입니다.  NetApp Disaster Recovery 미리 보기를 사용하면 Amazon FSx for ONTAP 을 사용하여 AWS의 VMware Cloud(VMC)에서 NetApp 스토리지를 실행하는 온프레미스 NFS 기반 VMware 워크로드를 보호할 수 있습니다.

link:https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["NetApp Disaster Recovery 에 대해 자세히 알아보세요"] .
